version: "3.8"
services:
  mongo:
    image: mongo:jammy
    container_name: mongo
    hostname: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mexpress
    hostname: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    networks:
      - backend
    restart: unless-stopped
    ports:
      - "8081:8081"

networks:
  backend: